services:
  backend:
    image: ghcr.io/hsse-tech/hsse-tech-backend-dev
    container_name: hsse-tech-backend-dev
    networks:
      - hsse-tech-internal-dev
    ports:
      - "8090:8080"
    env_file: "~/dev.env"

networks:
    hsse-tech-internal-dev:
      name: hsse-tech-internal-dev
      external: true
