name: Docker container build
on: 
  push:
    tags:
      - "*"
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
      - name: Build service
        uses: docker/build-push-action@v5.1.0
        with:
          file: ./Dockerfile
          tags: hsse-tech/hsse-tech-backend:${{GITHUB_REF/refs\/tags\//}}
          
