name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/hsse-tech/hsse-tech-backend-dev:${{steps.date.outputs.date}}
  deploy:
    runs-on: ubuntu-latest  
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Copy compose file to remote
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_DEV_HOST }}
          username: ${{ secrets.DEPLOY_DEV_USERNAME }}
          password: ${{ secrets.DEPLOY_DEV_KEY }}
          port: 22
          source: docker-compose.dev.yaml
          target: ~/web/dev

      - name: Run app
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_DEV_HOST }}
          username: ${{ secrets.DEPLOY_DEV_USERNAME }}
          password: ${{ secrets.DEPLOY_DEV_KEY }}
          port: 22
          script: |
            cd ~/web/dev
            sudo docker compose -f ./docker-compose.dev.yaml pull
            sudo docker compose -f ./docker-compose.dev.yaml up -d
