name: Production deployment

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tag
        run: echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 'ghcr.io/hsse-tech/hsse-tech-backend-prod:${{env.TAG}}, ghcr.io/hsse-tech/hsse-tech-backend-prod:latest'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Copy compose file to remote
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_PROD_HOST }}
          username: ${{ secrets.DEPLOY_PROD_USERNAME }}
          password: ${{ secrets.DEPLOY_PROD_PASSWORD }}
          port: 22
          source: docker-compose.prod.yaml
          target: ~/web/prod

      - name: Run app
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_PROD_HOST }}
          username: ${{ secrets.DEPLOY_PROD_USERNAME }}
          password: ${{ secrets.DEPLOY_PROD_KEY }}
          port: 22
          script: |
            cd ~/web/prod
            sudo docker compose -f ./docker-compose.prod.yaml pull
            sudo docker compose -f ./docker-compose.prod.yaml up -d
