name: Docker Image CI

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/hsse-tech/hsse-tech-backend-dev:$(date +%s)
    - name: Push the Docker image
      run: docker push ghcr.io/hsse-tech/hsse-tech-backend-dev:$(date +%s)
